### ISSUE TITLE
Possible to build gmp on windows?

### ISSUE THREAD

**Issue by flothesof** [conda-forge/gmp-feedstock#20]
Hi,
in an effort to bring pygalmesh to osx and win users, I've been investigating the conda-forge build (see PR here: https://github.com/conda-forge/staged-recipes/pull/11457). However, pygalmesh depends on gmp, which is not built for windows. 

Would it be possible to build gmp for windows? Has this been investigated before? Are there known difficulties? The official gmp website mentions this:

> GMP's main target platforms are Unix-type systems, such as GNU/Linux, Solaris, HP-UX, Mac OS X/Darwin, BSD, AIX, etc. It also is known to work on Windows in both 32-bit and 64-bit mode. 

Thanks for your input.
Best regards,

Florian

**Comment by nehaljwani** [comment]
As I mentioned in the thread, you can use mpir on Windows.

**Comment by flothesof** [comment]
Ah, sorry, I hadn't seen it. Thank you!
