### ISSUE TITLE
Windows Build

### ISSUE THREAD

**Issue by saraedum** [conda-forge/gmp-feedstock#34]
There is no Windows build of GMP here. I'm aware of #20 but I think MPIR is less well supported than it used to be so we are starting to see build problems with using MPIR instead of GMP, e.g., https://github.com/conda-forge/libflint-feedstock/pull/32 and https://github.com/conda-forge/gmpy2-feedstock/pull/37.

Is there a strong reason not to try to build GMP for Windows?

**Comment by saraedum** [comment]
cc @isuruf

**Comment by isuruf** [comment]
GMP does not support compiling with MSVC. We might have to use MinGW with UCRT.

**Comment by saraedum** [comment]
> GMP does not support compiling with GMP

You meant Windows I guess?

I see. I never checked, I just saw mentions of their changelog about performance improvements on Windows. So I assumed that one can just compile it with an autotools setup on Windows.

**Comment by isuruf** [comment]
Yeah, meant MSVC

**Comment by isuruf** [comment]
Have builds now
